---
version: '3'

services:
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
  api_service:
    restart: always
    build: 
      context: ./
      dockerfile: ./src/api_service/Dockerfile
    ports:
      - 80:8000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
  redis:
    image: redis:7.0
    ports:
      - 6379:6379
  db_service:
    restart: always
    build: 
      context: ./
      dockerfile: ./src/db_service/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    command: python db.py
  distance_service:
    restart: always
    build: 
      context: ./
      dockerfile: ./src/distance_service/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: python distance.py
  email_service:
    restart: always
    build: 
      context: ./
      dockerfile: ./src/email_service/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    command: python emails.py
