---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distance
  labels:
    app: distance
spec:
  selector:
    matchLabels:
      app: distance
  replicas: 1
  template:
    metadata:
      labels:
        app: distance
    spec:
      containers:
        - name: api
          image: jdvincent/distance:latest
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis_host | toJson  }}
            - name: REDIS_PORT
              value: {{ .Values.redis_port | toJson  }}
