---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
spec:
  selector:
    matchLabels:
      app: email
  replicas: 1
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: jdvincent/email:latest
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis_host | toJson  }}
            - name: REDIS_PORT
              value: {{ .Values.redis_port | toJson  }}
            - name: MONGO_HOST
              value: {{ .Values.mongo_host | toJson  }}
            - name: MONGO_PORT
              value: {{ .Values.mongo_port | toJson  }}
